id: f678a3c2e84b4516b86d2d32e6c3a163
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_308-Questions_Regarding_Death_and_Transmigration-v2
  language: bo
  author: ''
  volume: {}
